ALTER TYPE "public"."AppUpdateEventType" ADD VALUE IF NOT EXISTS 'DOWNLOAD_START';
ALTER TYPE "public"."AppUpdateEventType" ADD VALUE IF NOT EXISTS 'DOWNLOAD_DONE';
ALTER TYPE "public"."AppUpdateEventType" ADD VALUE IF NOT EXISTS 'VERIFY_FAILED';
ALTER TYPE "public"."AppUpdateEventType" ADD VALUE IF NOT EXISTS 'INSTALL_CLICK';
ALTER TYPE "public"."AppUpdateEventType" ADD VALUE IF NOT EXISTS 'OTA_READY';
ALTER TYPE "public"."AppUpdateEventType" ADD VALUE IF NOT EXISTS 'OTA_RELOAD';
