Match User leader-sentry-dev-tunnel
    PasswordAuthentication no
    PubkeyAuthentication yes
    AllowTcpForwarding remote
    PermitListen 127.0.0.1:19001
    GatewayPorts no
    X11Forwarding no
    AllowAgentForwarding no
    PermitTTY no
Match all
