import { Prisma } from '@prisma/client';

import { buildQueuedOrderPayload } from '../src/modules/onec/onec.orderQueuePayload';

describe('client order 1C queue payload', () => {
  it('preserves selected package, base quantity and line amount for packaged goods', () => {
    const deliveryDate = new Date('2026-06-28T00:00:00.000Z');
    const order = {
      id: 10,
      guid: 'order-guid',
      source: 'MANAGER_APP',
      revision: 12,
      syncState: 'QUEUED',
      status: 'QUEUED',
      createdAt: new Date('2026-06-27T10:00:00.000Z'),
      updatedAt: new Date('2026-06-27T10:05:00.000Z'),
      queuedAt: new Date('2026-06-27T10:06:00.000Z'),
      sentTo1cAt: null,
      deliveryDate,
      comment: 'Комментарий',
      currency: 'RUB',
      totalAmount: new Prisma.Decimal(2000),
      generalDiscountPercent: null,
      generalDiscountAmount: null,
      exportAttempts: 0,
      lastExportError: null,
      isPostedIn1c: false,
      postedAt1c: null,
      hasRealization: false,
      realizationDetectedAt: null,
      cancelRequestedAt: null,
      cancelReason: null,
      last1cError: null,
      sourceUpdatedAt: new Date('2026-06-27T10:06:00.000Z'),
      organization: { guid: 'organization-guid', name: 'Организация', code: 'ORG', isActive: true },
      counterparty: { guid: 'counterparty-guid', name: 'Контрагент', inn: '5400000000', kpp: '540001001', isActive: true },
      agreement: { guid: 'agreement-guid', name: 'Соглашение', isActive: true },
      contract: { guid: 'contract-guid', number: 'Д-1', date: null, isActive: true },
      warehouse: { guid: 'warehouse-guid', name: 'Склад', isActive: true, isDefault: true, isPickup: false },
      deliveryAddress: { guid: 'address-guid', name: 'Адрес', fullAddress: 'Новосибирск', isActive: true },
      createdByUser: {
        id: 1,
        firstName: 'Алексей',
        lastName: 'Борховецкий',
        middleName: null,
        email: 'user@example.com',
        employeeProfile: {
          onecUserGuid: 'manager-guid',
          onecPhysicalPersonGuid: 'physical-person-guid',
        },
      },
      items: [
        {
          id: 100,
          lineGuid: 'line-guid-1',
          quantity: new Prisma.Decimal(2),
          quantityBase: new Prisma.Decimal(20),
          basePrice: new Prisma.Decimal(100),
          price: new Prisma.Decimal(100),
          isManualPrice: false,
          manualPrice: null,
          priceSource: 'price-type',
          isCancelled: false,
          cancelReasonGuid: null,
          cancelReasonName: null,
          cancelReason: null,
          cancelledAmount: null,
          priceType: { guid: 'price-type-guid', name: 'Прайс' },
          discountPercent: null,
          appliedDiscountPercent: null,
          lineAmount: new Prisma.Decimal(2000),
          comment: 'строка',
          product: {
            guid: 'product-guid',
            name: 'Товар 10 кг',
            sku: 'UT-1',
            article: 'ART-1',
            isActive: true,
          },
          package: {
            guid: 'box-10',
            name: 'кор (10 кг)',
            isDefault: false,
          },
          unit: { guid: 'kg', name: 'Килограмм', symbol: 'кг' },
        },
        {
          id: 101,
          lineGuid: 'line-guid-manual',
          quantity: new Prisma.Decimal(3),
          quantityBase: new Prisma.Decimal(3),
          basePrice: new Prisma.Decimal(150),
          price: new Prisma.Decimal(150),
          isManualPrice: true,
          manualPrice: new Prisma.Decimal(150),
          priceSource: 'manual',
          isCancelled: false,
          cancelReasonGuid: null,
          cancelReasonName: null,
          cancelReason: null,
          cancelledAmount: null,
          priceType: null,
          discountPercent: null,
          appliedDiscountPercent: null,
          lineAmount: new Prisma.Decimal(450),
          comment: '',
          product: {
            guid: 'manual-product-guid',
            name: 'Товар с ручной ценой',
            sku: 'UT-2',
            article: 'ART-2',
            isActive: true,
          },
          package: null,
          unit: { guid: 'pcs', name: 'Штука', symbol: 'шт' },
        },
      ],
    };

    const payload = buildQueuedOrderPayload(order as any);

    expect(payload).toMatchObject({
      guid: 'order-guid',
      appGuid: 'order-guid',
      revision: 12,
      deliveryDate,
      totalAmount: 2000,
      manager: {
        guid: 'manager-guid',
        physicalPersonGuid: 'physical-person-guid',
        name: 'Борховецкий Алексей',
      },
      items: [
        {
          lineGuid: 'line-guid-1',
          appLineGuid: 'line-guid-1',
          quantity: 2,
          quantityBase: 20,
          basePrice: 100,
          price: 100,
          manualPrice: null,
          lineAmount: 2000,
          package: {
            guid: 'box-10',
            name: 'кор (10 кг)',
          },
          unit: { guid: 'kg', name: 'Килограмм', symbol: 'кг' },
          priceType: { guid: 'price-type-guid', name: 'Прайс' },
        },
        {
          lineGuid: 'line-guid-manual',
          product: { guid: 'manual-product-guid', name: 'Товар с ручной ценой' },
          quantity: 3,
          quantityBase: 3,
          basePrice: 150,
          price: 150,
          manualPrice: 150,
          isManualPrice: true,
          priceSource: 'manual',
          lineAmount: 450,
          priceType: null,
        },
      ],
    });
  });
});
